### ISSUE TITLE
Packages unexisting.

### ISSUE THREAD

**Issue by Soraiko** [Aida-Enna/PSO2JP_Token_Generator#3]
Maybe one day, the miracle will happen that a github repository solution builds without error......
Costura.Fody and Fody doesn't exist on Nuget.org.
Newtonsoft.Json version 10 doesn't exist on Nuget.org either. The latest is version 8.

**Comment by Aida-Enna** [comment]
I won't be home for a bit, but at a glance nuget.org shows the latest
version of Newtonsoft.Json is 13.0.1, with version 10 having come out in
2017.

https://www.nuget.org/packages/Newtonsoft.Json/#versions-body-tab

I'll freshly clone the repo and double check when I get home, though.

**Comment by Soraiko** [comment]
Sorry for this angry and dumb comment that finally solved pretty easily.
Thanks for replying accurately it's sweet.
I forked your TokenGenerator and added a feature to automatically log in the SEGA ID using a not very secure method.
(You'll get what I mean if you take a look at it)
I carefully mentionned that this is a fork and that this feature is not suggested at all in your initial work and warned potential users that it's unsecure.
